from enum import Enum


class AminoAcids(Enum):
    tryptophan = "Tryphonphan"
    stop = "Stop"
    cysteine = "Cysteine"
    tyrosine = "Tyrosine"
    serine = "Serine"
    leucine = "Leucine"
    phenyl_alanine = "Phenyl-Alanine"
    glycine = "Glycine"
    glutamic_acid = "Glutamic Acid"
    aspartic_acid = "Aspartic Acid"
    alanine = "Alanine"
    valine = "Valine"
    arginine = "Arginine"
    lysine = "Lysine"
    asparagine = "Asparagine"
    threonine = "Threonine"
    methionine = "Methionine"
    isoleucine = "Isoleucine"
    glutamine = "Glutamine"
    histidine = "Histidine"
    proline = "Proline"
